### ISSUE TITLE
ist the v1.1.2-beta.1 version ready for production?

### ISSUE THREAD

**Issue by gibso** [ember-fastboot/fastboot-app-server#101]
Hey there,

Would you recommend to use the v1.1.2-beta.1 version in production or should i stick with the v1.1.0 version for that?

Thank you,
Oliver.

**Comment by snewcomer** [comment]
Over the coming months, we will work on resolving some issues and taking care of existing PR's.  Hopefully get a recent version bump out soon-ish.  I'll let you know when it does come out!

**Comment by snewcomer** [comment]
@gibso Looks like 2.0 was released!

**Comment by gibso** [comment]
That's fantastic, thank you :-)
