### ISSUE TITLE
ember-cli expected ./server/index.js to be the entry for your mock or proxy server

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-fastboot/fastboot-app-server#113]
If I follow the README quickstart literally and create a root-level server.js file, `ember s` breaks with the error: 

```
ember-cli expected ./server/index.js to be the entry for your mock or proxy server


Stack Trace and Error Report: /var/folders/r4/wf5lz02n6y3fhyz2btpmrjyw0000gn/T/error.dump.e4e3890cc1b50d262fb7970ba3ee8a23.log
```

https://github.com/ember-fastboot/fastboot-app-server#quick-start

The solution is to name the file literally anything else, such as fastboot-server.js

see https://github.com/ember-cli/ember-cli/issues/2903#issuecomment-68937347

**Comment by rwjblue** [comment]
The README was just updated to suggest using `fastboot-server.js` instead of `server.js`, that should resolve this I think.
