### ISSUE TITLE
addon work in ember-cli-fastboot but not in fast boot-app-server

### ISSUE THREAD

**Issue by vreyesd** [ember-fastboot/fastboot-app-server#27]
I create a little test project https://github.com/vreyesd/testMomentFastboot . It run well in fastboot mode with `ember fastboot` but with boot-app-server (server in server folder) have a error

`Error while processing route: home Cannot find module 'moment-timezone' Error: Cannot find module 'moment-timezone'`

**Comment by kyleshevlin** [comment]
Looking at your sample application, I believe you are not including `moment` correctly. For third-party npm modules, it is recommended to use the `ember-browserify` addon. Install the addon, and change the import of Moment to:

```
import moment from 'npm:moment';
```

And see if this resolves your issue.
