### ISSUE TITLE
Fastboot App Server seems extremely memory intensive

### ISSUE THREAD

**Issue by t4t5** [ember-fastboot/fastboot-app-server#31]
I'm running a Node server on Heroku Standard Tier 1X.

Using Fastboot App Server I constantly get the "Memory Quota Exceeded" error message. The memory usage keeps going up until the app ultimately crashes and has to restart.

<img width="338" alt="screen shot 2016-10-10 at 16 01 35" src="https://cloud.githubusercontent.com/assets/2598660/19238726/28aec6a6-8f03-11e6-8f7e-f7ba3dd31350.png">

Is Fastboot just naturally memory intensive or is there any way to fix this problem?

**Comment by ptomasroos** [comment]
I'm not sure but it might make sense to disable etag support in the static serving from express.

http://expressjs.com/en/api.html#express.static

Seems to be enabled by default.

Used https://github.com/ember-fastboot/fastboot-app-server/blob/c5f02155c2f6846995d7c113098395bcd1f83e6a/src/express-http-server.js#L39

**Comment by danmcclain** [comment]
This likely tracks towards ember-fastboot/fastboot#100, as there were references that would not get cleaned up, let's reexamine once that PR lands and see if we can close this then

**Comment by tomdale** [comment]
So far, all of the cases of memory leaks we've dug into have come from application code. For example, if anyone ever inadvertently initializes an array on a class prototype instead of an instance (like including an array in a call to `Ember.Object.extend()`, for example), this array will never be GCed.

I wrote down the steps I took to debug memory leaks in FastBoot [here](https://github.com/ember-fastboot/fastboot/pull/100#issuecomment-275805511), let me know if that's helpful in tracking the root issue down.

**Comment by stefanpenner** [comment]
@tomdale i suspect we can close this guy. I agree no obvious leaks in fastboot itself.  But it is very common for legitimate app leaks to be really bad in fastboot.

@t4t5 an additional resource (for debugging an investigating leaks in your ember app) is an walk-through-guide of memory leak fixing/hunting https://github.com/ember-best-practices/memory-leak-examples.

This may help it helped our engineers address many leaks that became more much prevalent in fastboot. 

---

If i have misunderstood and there is a more specific issue visible here. Please comment with those details and i can reopen.

**Comment by allthesignals** [comment]
Out of curiosity, @t4t5 were you able to find out anything else about this?

**Comment by t4t5** [comment]
@allthesignals I was not unfortunately and ended up moving away from FastBoot altogether because I simply couldn't find what caused the memory leak. 😕

**Comment by allthesignals** [comment]
@t4t5 hmm okay. Here's what I'm going to try: deploy an "empty" Ember app, then deploy parts of my real Ember app with several modules commented out. I have some suspicions of where the leaks are happening, but it'd be good to start with sanity-checking the source of the problem.
