### ISSUE TITLE
Handle deprecation of BaseURL

### ISSUE THREAD

**Issue by danmcclain** [ember-fastboot/fastboot-app-server#42]
Should support RootURL for asset serving, effectively need this fix here: https://github.com/ember-fastboot/ember-cli-fastboot/pull/273

**Comment by danmcclain** [comment]
Takes over for: https://github.com/ember-fastboot/fastboot-express-middleware/issues/12

**Comment by varoot** [comment]
I'm trying to figure out how to fix the problem running this with projects that specify `rootURL`. FastbootAppServer doesn't seem to have access to `rootURL` property, does it?

**Comment by kratiahuja** [comment]
Closing this. We now rely on ember-cli to do this. Please try the latest 1.x release let us know if this isn't fixed for you.
