### ISSUE TITLE
Adding custom routes to the default ExpressHTTPServer

### ISSUE THREAD

**Issue by buschtoens** [ember-fastboot/fastboot-app-server#5]
It would be great if users could somehow hook into the default `ExpressHTTPServer`. This way, if they want to just add a single route, they don't need to ship their own server.

I'm currently working on a GitLab flavored FastBoot App server, that doesn't actively poll for new builds, but gets passively notified by a web hook. I'd rather add a secret callback route than starting a second HTTP server on a different port.

**Comment by buschtoens** [comment]
Access to the `Worker` would also be required, so that IPC can be used.

Is this too complex for the default implementation?

**Comment by courthead** [comment]
The server is accessible. I'm doing something like this:

```js
const server = new FastBootAppServer(serverOptions);
if (server.worker) {
  const app = server.worker.httpServer.app;
  app.use(logger('dev'));
  app.use(bodyParser.json());
  // etc
}
```

There seems to be a pull request that makes this a bit easier: https://github.com/ember-fastboot/fastboot-app-server/pull/12

**Comment by courthead** [comment]
I created a pull request for this: https://github.com/ember-fastboot/fastboot-app-server/pull/14. Here's how you can use it:

First, install the code from pull request in your project: `npm install --save ember-fastboot/fastboot-app-server#pull/14/head`

Then, in your `app.js` or `server.js` or whatever you're using:

```js
const ExpressHTTPServer = require('fastboot-app-server/lib/express-http-server');
const FastBootAppServer = require('fastboot-app-server');
const apiRoutes = require('./routes/api');
const bodyParser = require('body-parser');
const cookieParser = require('cookie-parser');

const httpServer = new ExpressHTTPServer();
const app = httpServer.app;
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use('/api', apiRoutes);

const server = new FastBootAppServer({
  httpServer,
  // you should also specify notifier, cache, distPath, downloader, etc
});

server.start();
```

**Comment by rwjblue** [comment]
I believe this was solved with https://github.com/ember-fastboot/fastboot-app-server/commit/178ac5933e58dd7e72c15808930ff8f002f52013.

Please review, and let me know if that doesn't solve your needs here.  Will close for now...
