### ISSUE TITLE
Run FastBoot within an existing express application, is it possible ?

### ISSUE THREAD

**Issue by linuxenko** [ember-fastboot/fastboot-app-server#84]
Hi 🦄 

I would like to run all applications (api and front-end part e.g. fastboot server) with a single instance. It seems to me as simple as connecting the middleware and configuration of the fastboot and already existing routes. But .. yeah, it is not so simple as I thought. Does my idea worth any further tryings ? Is it possible at all ?

**Comment by sdhull** [comment]
I believe what you're looking for is something like [this](https://github.com/ember-fastboot/fastboot-express-middleware)?

**Comment by linuxenko** [comment]
Looks like exactly what I was looking for. 
ty @sdhull
